---
title: "Movement Explore 2"
output: html_notebook
---


# Setup
```{r include=FALSE}
library(tidyverse)
library(sf)
library(mapview)
library(plotly)

path_sp <- "C:/OD/Foursquare ITP/Projects - WMATA Datamart"

path_data <-
  file.path(
    path_sp,
    "Task 3 - Bus Priority",
    "Data",
    "01-Interim"
  )

```

```{r}
knitr::opts_chunk$set(echo = FALSE)
```


Define useful functions
```{r}

load_rawnav <- 
  function(thepath){
    suppressWarnings({
      read_csv(
        thepath,
        col_types = cols(
          X1 = col_double(),
          index_loc = col_double(),
          lat = col_double(),
          long = col_double(),
          heading = col_double(),
          door_state = col_character(),
          veh_state = col_character(),
          odom_ft = col_double(),
          sec_past_st = col_double(),
          sat_cnt = col_double(),
          stop_window = col_character(),
          blank = col_double(),
          lat_raw = col_double(),
          long_raw = col_double(),
          row_before_apc = col_double(),
          route_pattern = col_character(),
          pattern = col_double(),
          index_run_start = col_double(),
          index_run_end = col_double(),
          filename = col_character(),
          start_date_time = col_datetime(format = ""),
          route = col_character(),
          wday = col_character(),
          odom_ft_next = col_double(),
          sec_past_st_next = col_double(),
          odom_ft_next3 = col_double(),
          sec_past_st_next3 = col_double(),
          secs_marg = col_double(),
          odom_ft_marg = col_double(),
          fps_next = col_double(),
          fps_next3 = col_double()
        )
      )
    })
    
  }


cleanup_things <- function(rawnav){
  rawnav %>%
    st_as_sf(
      ., 
      coords = c("long", "lat"),
      crs = 4326L, #WGS84
      agr = "constant"
    ) %>%
    mutate(
      mins_past_st = sec_past_st / 60,
      mph_next = fps_next / 1.467,
      mph_next3 = fps_next3 / 1.467,
      fps_next_lead = lead(fps_next),
      fps_next3_lead = lead(fps_next3),
      accel_next = (fps_next_lead - fps_next) / (sec_past_st_next - sec_past_st),
      accel_next3 = (fps_next3_lead - fps_next3) / (sec_past_st_next3 - sec_past_st),
      accel_next = round(accel_next,3),
      accel_next3 = round(accel_next3,3),
      accel_mph_next = accel_next / 1.467,
      accel_mph_next3 = accel_next3 / 1.467
    )
}

plot_rawnav <-
  function(rawnav, var, thetitle = NULL){
    if (is.null(thetitle)){
      thetitle = rlang::as_label(enquo(var))
    }
    
    g <- 
      ggplot(
        data = rawnav
      ) +
      geom_line(
        aes(
          y = odom_ft,
          x = mins_past_st
        ),
        color = "grey80"
      ) +
      geom_point(
        aes(
          color = {{var}},
          y = odom_ft,
          x = mins_past_st
        )
      ) +
      xlab("Time Past Trip Start (Minutes)") +
      ylab("Trip Odometer Distance (Feet)") +
      scale_color_gradient2(
        low = "#d7191c",
        mid = "#ffffbf",
        high = "#1a9641"
        # low = ("red"),
        # mid = ("grey90"),
        # high = ("green")
        # low = scales::muted("red"),
        # mid = scales::muted("yellow"),
        # high = scales::muted("green")
      ) +
      theme_minimal() +
      guides(color=guide_legend(title=thetitle))
      
    
    # g
    ggplotly(g, dynamicTicks = TRUE)
  }

plot_dots <-
  function(rawnav){
    
    g <- 
      ggplot(
        data = rawnav
      ) +
      geom_line(
        aes(
          y = odom_ft,
          x = sec_past_st
        ),
        color = "grey80"
      ) +
      geom_point(
        aes(
          y = odom_ft,
          x = sec_past_st
        )
      ) +
      xlab("Time Past Trip Start (Minutes)") +
      ylab("Trip Odometer Distance (Feet)") +
      theme_minimal() 
    # g
    ggplotly(g, dynamicTicks = TRUE)
  }
```


# Case 1
These are from:
testfile = "rawnav07231210220.txt"
testindex = 9877

## Unfixed
```{r}
rawnav_unfixed <-
  load_rawnav(
    file.path(path_data,"test_checkunfixed4.csv")
  ) %>%
  mutate(
    mins_past_st = sec_past_st / 60,
    sec_past_st_next = lead(sec_past_st),
    odom_ft_next = lead(odom_ft),
    fps_next = (odom_ft_next - odom_ft) / (sec_past_st_next - sec_past_st),
    fps_next_lag = lag(fps_next),
    sec_past_st_lag = lag(sec_past_st),
    accel = (fps_next - fps_next_lag) / (sec_past_st_next - sec_past_st_lag)
  ) 
```

```{r, fig.width=6, fig.height=4}
plot_rawnav(rawnav_unfixed,accel)
```



## "fixed"
still seeing issues at odom_ft: 13673 and 14762
min past st 14.7

13667 is where you see first big drop
```{r}
rawnav_tfixed4 <-
  load_rawnav(
    file.path(path_data,"test_checkfixed4.csv")
  ) %>%
  mutate(
    mins_past_st = sec_past_st / 60,
    accel_next_mph = accel_next / 1.467
  )


# What is the speed we shou
```

```{r, fig.width=6, fig.height=4}
plot_rawnav(rawnav_tfixed4,accel_next_mph)    
```

```{r, fig.width=6, fig.height=4}
plot_rawnav(rawnav_tfixed4,fps_next)    
```

## "fixed" 2
added in the spline after the agg

```{r}
rawnav_tfixed5 <-
  load_rawnav(
    file.path(path_data,"test_checkfixed5.csv")
  ) %>%
  mutate(
    mins_past_st = sec_past_st / 60,
    accel_next_mph = accel_next / 1.467
  )
```

```{r, fig.width=6, fig.height=4}
plot_rawnav(rawnav_tfixed5,accel_next_mph)    
```

```{r, fig.width=6, fig.height=4}
plot_rawnav(rawnav_tfixed5,fps_next)    
```

## "fixed" 3

```{r}
rawnav_tfixed6 <-
  load_rawnav(
    file.path(path_data,"test_checkfixed6.csv")
  ) %>%
  mutate(
    mins_past_st = sec_past_st / 60,
    accel_next_mph = accel_next / 1.467
  )
```

```{r, fig.width=6, fig.height=4}
plot_rawnav(rawnav_tfixed6,accel_next_mph)    
```


# Case 2

testfile = "rawnav04475210210.txt"
testindex = 4279

on this one, ran into some issues with door open and close on the 
same second

# unfixed

```{r}
rawnav_unfixed2 <-
  load_rawnav(
    file.path(path_data,"test_broken2.csv")
  ) %>%
  mutate(
    mins_past_st = sec_past_st / 60,
    sec_past_st_next = lead(sec_past_st),
    odom_ft_next = lead(odom_ft),
    fps_next = (odom_ft_next - odom_ft) / (sec_past_st_next - sec_past_st),
    fps_next_lag = lag(fps_next),
    sec_past_st_lag = lag(sec_past_st),
    accel = (fps_next - fps_next_lag) / (sec_past_st_next - sec_past_st_lag)
  ) 
```

```{r, fig.width=6, fig.height=4}
rawnav_unfixed2 %>%
  mutate(
    door_state = as.numeric(parse_factor(door_state))
  ) %>%
  plot_rawnav(.,door_state)
```


